--
-- Autogenerated by Thrift
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
-- @generated
--


require 'Thrift'
require 'social_network_ttypes'

MediaFilterServiceClient = __TObject.new(__TClient, {
  __type = 'MediaFilterServiceClient'
})

function MediaFilterServiceClient:MediaFilter(req_id, media_ids, media_types, media_data_list, carrier)
  self:send_MediaFilter(req_id, media_ids, media_types, media_data_list, carrier)
  return self:recv_MediaFilter(req_id, media_ids, media_types, media_data_list, carrier)
end

function MediaFilterServiceClient:send_MediaFilter(req_id, media_ids, media_types, media_data_list, carrier)
  self.oprot:writeMessageBegin('MediaFilter', TMessageType.CALL, self._seqid)
  local args = MediaFilter_args:new{}
  args.req_id = req_id
  args.media_ids = media_ids
  args.media_types = media_types
  args.media_data_list = media_data_list
  args.carrier = carrier
  args:write(self.oprot)
  self.oprot:writeMessageEnd()
  self.oprot.trans:flush()
end

function MediaFilterServiceClient:recv_MediaFilter(req_id, media_ids, media_types, media_data_list, carrier)
  local fname, mtype, rseqid = self.iprot:readMessageBegin()
  if mtype == TMessageType.EXCEPTION then
    local x = TApplicationException:new{}
    x:read(self.iprot)
    self.iprot:readMessageEnd()
    error(x)
  end
  local result = MediaFilter_result:new{}
  result:read(self.iprot)
  self.iprot:readMessageEnd()
  if result.success ~= nil then
    return result.success
  elseif result.se then
    error(result.se)
  end
  error(TApplicationException:new{errorCode = TApplicationException.MISSING_RESULT})
end
MediaFilterServiceIface = __TObject:new{
  __type = 'MediaFilterServiceIface'
}


MediaFilterServiceProcessor = __TObject.new(__TProcessor
, {
 __type = 'MediaFilterServiceProcessor'
})

function MediaFilterServiceProcessor:process(iprot, oprot, server_ctx)
  local name, mtype, seqid = iprot:readMessageBegin()
  local func_name = 'process_' .. name
  if not self[func_name] or ttype(self[func_name]) ~= 'function' then
    iprot:skip(TType.STRUCT)
    iprot:readMessageEnd()
    x = TApplicationException:new{
      errorCode = TApplicationException.UNKNOWN_METHOD
    }
    oprot:writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
    x:write(oprot)
    oprot:writeMessageEnd()
    oprot.trans:flush()
  else
    self[func_name](self, seqid, iprot, oprot, server_ctx)
  end
end

function MediaFilterServiceProcessor:process_MediaFilter(seqid, iprot, oprot, server_ctx)
  local args = MediaFilter_args:new{}
  local reply_type = TMessageType.REPLY
  args:read(iprot)
  iprot:readMessageEnd()
  local result = MediaFilter_result:new{}
  local status, res = pcall(self.handler.MediaFilter, self.handler, args.req_id, args.media_ids, args.media_types, args.media_data_list, args.carrier)
  if not status then
    reply_type = TMessageType.EXCEPTION
    result = TApplicationException:new{message = res}
  elseif ttype(res) == 'ServiceException' then
    result.se = res
  else
    result.success = res
  end
  oprot:writeMessageBegin('MediaFilter', reply_type, seqid)
  result:write(oprot)
  oprot:writeMessageEnd()
  oprot.trans:flush()
end

-- HELPER FUNCTIONS AND STRUCTURES

MediaFilter_args = __TObject:new{
  req_id,
  media_ids,
  media_types,
  media_data_list,
  carrier
}

function MediaFilter_args:read(iprot)
  iprot:readStructBegin()
  while true do
    local fname, ftype, fid = iprot:readFieldBegin()
    if ftype == TType.STOP then
      break
    elseif fid == 1 then
      if ftype == TType.I64 then
        self.req_id = iprot:readI64()
      else
        iprot:skip(ftype)
      end
    elseif fid == 2 then
      if ftype == TType.LIST then
        self.media_ids = {}
        local _etype377, _size374 = iprot:readListBegin()
        for _i=1,_size374 do
          local _elem378 = iprot:readI64()
          table.insert(self.media_ids, _elem378)
        end
        iprot:readListEnd()
      else
        iprot:skip(ftype)
      end
    elseif fid == 3 then
      if ftype == TType.LIST then
        self.media_types = {}
        local _etype382, _size379 = iprot:readListBegin()
        for _i=1,_size379 do
          local _elem383 = iprot:readString()
          table.insert(self.media_types, _elem383)
        end
        iprot:readListEnd()
      else
        iprot:skip(ftype)
      end
    elseif fid == 4 then
      if ftype == TType.LIST then
        self.media_data_list = {}
        local _etype387, _size384 = iprot:readListBegin()
        for _i=1,_size384 do
          local _elem388 = iprot:readString()
          table.insert(self.media_data_list, _elem388)
        end
        iprot:readListEnd()
      else
        iprot:skip(ftype)
      end
    elseif fid == 5 then
      if ftype == TType.MAP then
        self.carrier = {}
        local _ktype390, _vtype391, _size389 = iprot:readMapBegin() 
        for _i=1,_size389 do
          local _key393 = iprot:readString()
          local _val394 = iprot:readString()
          self.carrier[_key393] = _val394
        end
        iprot:readMapEnd()
      else
        iprot:skip(ftype)
      end
    else
      iprot:skip(ftype)
    end
    iprot:readFieldEnd()
  end
  iprot:readStructEnd()
end

function MediaFilter_args:write(oprot)
  oprot:writeStructBegin('MediaFilter_args')
  if self.req_id ~= nil then
    oprot:writeFieldBegin('req_id', TType.I64, 1)
    oprot:writeI64(self.req_id)
    oprot:writeFieldEnd()
  end
  if self.media_ids ~= nil then
    oprot:writeFieldBegin('media_ids', TType.LIST, 2)
    oprot:writeListBegin(TType.I64, #self.media_ids)
    for _,iter395 in ipairs(self.media_ids) do
      oprot:writeI64(iter395)
    end
    oprot:writeListEnd()
    oprot:writeFieldEnd()
  end
  if self.media_types ~= nil then
    oprot:writeFieldBegin('media_types', TType.LIST, 3)
    oprot:writeListBegin(TType.STRING, #self.media_types)
    for _,iter396 in ipairs(self.media_types) do
      oprot:writeString(iter396)
    end
    oprot:writeListEnd()
    oprot:writeFieldEnd()
  end
  if self.media_data_list ~= nil then
    oprot:writeFieldBegin('media_data_list', TType.LIST, 4)
    oprot:writeListBegin(TType.STRING, #self.media_data_list)
    for _,iter397 in ipairs(self.media_data_list) do
      oprot:writeString(iter397)
    end
    oprot:writeListEnd()
    oprot:writeFieldEnd()
  end
  if self.carrier ~= nil then
    oprot:writeFieldBegin('carrier', TType.MAP, 5)
    oprot:writeMapBegin(TType.STRING, TType.STRING, ttable_size(self.carrier))
    for kiter398,viter399 in pairs(self.carrier) do
      oprot:writeString(kiter398)
      oprot:writeString(viter399)
    end
    oprot:writeMapEnd()
    oprot:writeFieldEnd()
  end
  oprot:writeFieldStop()
  oprot:writeStructEnd()
end

MediaFilter_result = __TObject:new{
  success,
  se
}

function MediaFilter_result:read(iprot)
  iprot:readStructBegin()
  while true do
    local fname, ftype, fid = iprot:readFieldBegin()
    if ftype == TType.STOP then
      break
    elseif fid == 0 then
      if ftype == TType.LIST then
        self.success = {}
        local _etype403, _size400 = iprot:readListBegin()
        for _i=1,_size400 do
          local _elem404 = iprot:readBool()
          table.insert(self.success, _elem404)
        end
        iprot:readListEnd()
      else
        iprot:skip(ftype)
      end
    elseif fid == 1 then
      if ftype == TType.STRUCT then
        self.se = ServiceException:new{}
        self.se:read(iprot)
      else
        iprot:skip(ftype)
      end
    else
      iprot:skip(ftype)
    end
    iprot:readFieldEnd()
  end
  iprot:readStructEnd()
end

function MediaFilter_result:write(oprot)
  oprot:writeStructBegin('MediaFilter_result')
  if self.success ~= nil then
    oprot:writeFieldBegin('success', TType.LIST, 0)
    oprot:writeListBegin(TType.BOOL, #self.success)
    for _,iter405 in ipairs(self.success) do
      oprot:writeBool(iter405)
    end
    oprot:writeListEnd()
    oprot:writeFieldEnd()
  end
  if self.se ~= nil then
    oprot:writeFieldBegin('se', TType.STRUCT, 1)
    self.se:write(oprot)
    oprot:writeFieldEnd()
  end
  oprot:writeFieldStop()
  oprot:writeStructEnd()
end