FROM intel/intel-optimized-tensorflow:2.9.1

#ENV http_proxy=http://proxy-fm.intel.com:911
#ENV https_proxy=http://proxy-fm.intel.com:912
#ENV no_proxy="10.105.159.2,10.105.159.2,10.105.159.0/24,10.250.0.0/16,10.254.0.0/15,10.253.0.0/16,127.0.0.1,localhost,.svc,.pod,.cluster.local,.svc.cluster.local,.intel.com"

COPY scripts /scripts
RUN git clone https://github.com/IntelAI/models.git

ENTRYPOINT benchmark.sh