#FROM ubuntu:16.04
#
#RUN apt-get update \
#  && apt-get install -y \
#    python3 \
#    python3-pip \
#  && pip3 install thrift

FROM python:3

#ENV http_proxy=http://proxy-fm.intel.com:911
#ENV https_proxy=http://proxy-fm.intel.com:912
#ENV no_proxy="10.105.159.2,10.105.159.2,10.105.159.0/24,10.250.0.0/16,10.254.0.0/15,10.253.0.0/16,127.0.0.1,localhost,.svc,.pod,.cluster.local,.svc.cluster.local,.intel.com"

RUN pip install thrift
