FROM intel/intel-optimized-tensorflow:2.9.1

#ENV http_proxy=http://proxy-fm.intel.com:911
#ENV https_proxy=http://proxy-fm.intel.com:912
#ENV no_proxy="10.105.159.2,10.105.159.2,10.105.159.0/24,10.250.0.0/16,10.254.0.0/15,10.253.0.0/16,127.0.0.1,localhost,.svc,.pod,.cluster.local,.svc.cluster.local,.intel.com"

COPY faster-rcnn /faster-rcnn
RUN pip install --no-cache-dir pillow==8.2.0 tensorflow-hub==0.12.0 matplotlib==3.5.2 numpy==1.19.2
WORKDIR /faster-rcnn


# ENV TF_ENABLE_ONEDNN_OPTS=1
# ENV OMP_NUM_THREADS=8
# # ENV KMP_AFFINITY=granularity=fine,verbose,compact,1,0
# ENV KMP_AFFINITY=granularity=fine,none,1,0
# ENTRYPOINT ["python", "MediaFilterService.py", "--num_intra_threads=8", "--num_inter_threads=2"]
# # ENTRYPOINT ["python", "MediaFilterService.py"]
