FROM tensorflow/tensorflow:devel

#ENV http_proxy=http://proxy-fm.intel.com:911
#ENV https_proxy=http://proxy-fm.intel.com:912
#ENV no_proxy="10.105.159.2,10.105.159.2,10.105.159.0/24,10.250.0.0/16,10.254.0.0/15,10.253.0.0/16,127.0.0.1,localhost,.svc,.pod,.cluster.local,.svc.cluster.local,.intel.com"

WORKDIR /tensorflow_src

RUN git checkout r2.5
RUN yes "" | python configure.py
# RUN bazel build --config=opt --copt=-mavx2 --local_cpu_resources=20 //tensorflow/tools/pip_package:build_pip_package
RUN bazel build --config=opt --copt=-mavx2 --local_cpu_resources=HOST_CPUS*.5 //tensorflow/tools/pip_package:build_pip_package && \
    ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip && \
    pip install --no-cache-dir /tmp/pip/tensorflow-2.5.0-cp36-cp36m-linux_x86_64.whl && \
    rm -rf /root/.cache
WORKDIR /
